### ISSUE TITLE
Finance::OFX::Parse::parse_file doesn't work.

### ISSUE THREAD

**Issue by harleypig** [bfoz/p5-Finance-OFX#4]
line 126 in Parse.pm there is a call to 'read_file' but there is no subroutine read_file define at this scope.

**Comment by bfoz** [comment]
Thanks for finding this. I don't have time to look into it right now, would you mind submitting a pull request?

**Comment by harleypig** [comment]
Certainly. Do you mind if I just 'use File::Slurp' and import the read_file subroutine?

**Comment by bfoz** [comment]
That works for me.
